version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql_libros
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librosdb
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d